import type { Express } from "express";

const TMDB_BASES = ["https://api.tmdb.org/3", "https://api.themoviedb.org/3"];
const TMDB_IMAGES = "https://image.tmdb.org/t/p/w500";
const YOUTUBE_BASE = "https://www.googleapis.com/youtube/v3";
const cache = new Map<string, { expires: number; value: unknown }>();
const CACHE_TTL = 10 * 60 * 1000;
const positiveWords = new Set("amazing awesome beautiful brilliant compelling excellent fantastic fascinating fun funny good great incredible love loved masterpiece perfect powerful remarkable solid stunning superb entertaining enjoyable emotional favorite well-written worth watch recommend".split(" "));
const negativeWords = new Set("awful bad boring confusing disappointing dislike disliked dull fails failure flat forgettable horrible hate hated lazy mediocre messy predictable poor terrible tedious weak worst waste wasted".split(" "));
const aspects: Record<string, string[]> = { Acting: ["acting", "actor", "actress", "cast", "performance"], Story: ["story", "plot", "writing", "script", "narrative", "character"], Visuals: ["visual", "cinematography", "effects", "animation", "scene"], Music: ["music", "soundtrack", "score", "song", "sound"], Pacing: ["pace", "pacing", "slow", "fast", "length"] };
function cacheGet<T>(key: string) { const item = cache.get(key); return item && item.expires > Date.now() ? item.value as T : null; }
function cacheSet<T>(key: string, value: T) { cache.set(key, { expires: Date.now() + CACHE_TTL, value }); return value; }
function image(path: string | null | undefined) { return path ? `${TMDB_IMAGES}${path}` : null; }
function errorMessage(error: unknown) { return error instanceof Error ? error.message.split(" for url:")[0] : "Provider request failed"; }
async function tmdb<T>(pathname: string, params: Record<string, string | number> = {}) {
  const key = process.env.TMDB_API_KEY;
  if (!key) throw new Error("TMDB_API_KEY is not configured on the server.");
  let lastError: unknown = null;
  for (const base of TMDB_BASES) {
    try {
      const url = new URL(`${base}${pathname}`);
      url.searchParams.set("api_key", key);
      Object.entries(params).forEach(([name, value]) => url.searchParams.set(name, String(value)));
      const cacheKey = `tmdb:${url.pathname}:${url.search}`;
      const old = cacheGet<T>(cacheKey);
      if (old) return old;
      const response = await fetch(url, { headers: { "Accept": "application/json" } });
      if (!response.ok) throw new Error(`TMDB returned ${response.status}`);
      return cacheSet(cacheKey, await response.json() as T);
    } catch (err) {
      lastError = err;
    }
  }
  throw lastError instanceof Error ? lastError : new Error("TMDB request failed");
}
function simplify(movie: any) { return { id: movie.id, title: movie.title, release_date: movie.release_date, overview: movie.overview, poster_url: image(movie.poster_path), backdrop_url: image(movie.backdrop_path), vote_average: movie.vote_average, popularity: movie.popularity }; }
async function details(id: string) { const data = await tmdb<any>(`/movie/${encodeURIComponent(id)}`, { append_to_response: "credits,videos" }); const trailer = (data.videos?.results || []).find((video: any) => video.site === "YouTube" && ["Trailer", "Teaser"].includes(video.type)); return { id: data.id, title: data.title, tagline: data.tagline, overview: data.overview, release_date: data.release_date, runtime: data.runtime, genres: (data.genres || []).map((genre: any) => genre.name), poster_url: image(data.poster_path), backdrop_url: image(data.backdrop_path), vote_average: data.vote_average, vote_count: data.vote_count, director: (data.credits?.crew || []).find((person: any) => person.job === "Director")?.name || null, cast: (data.credits?.cast || []).slice(0, 8).map((person: any) => ({ name: person.name, character: person.character })), trailer: trailer?.key ? { name: trailer.name, youtube_key: trailer.key, youtube_url: `https://www.youtube.com/watch?v=${trailer.key}`, youtube_embed_url: `https://www.youtube.com/embed/${trailer.key}` } : null }; }
async function reviews(title: string) { const key = process.env.YOUTUBE_API_KEY; if (!key) throw new Error("YOUTUBE_API_KEY is not configured on the server."); const search = new URL(`${YOUTUBE_BASE}/search`); Object.entries({ part: "snippet", q: `${title} movie review`, type: "video", maxResults: "5", relevanceLanguage: "en", order: "relevance", key }).forEach(([name, value]) => search.searchParams.set(name, value)); const searchResponse = await fetch(search); if (!searchResponse.ok) throw new Error(`YouTube returned ${searchResponse.status}`); const result: any[] = []; for (const item of (await searchResponse.json() as any).items || []) { const videoId = item.id?.videoId; if (!videoId) continue; const comments = new URL(`${YOUTUBE_BASE}/commentThreads`); Object.entries({ part: "snippet", videoId, maxResults: "40", order: "relevance", textFormat: "plainText", key }).forEach(([name, value]) => comments.searchParams.set(name, value)); const response = await fetch(comments); if (!response.ok) continue; for (const comment of (await response.json() as any).items || []) { const snippet = comment.snippet?.topLevelComment?.snippet; if (snippet?.textDisplay) result.push({ text: snippet.textDisplay, source: "YouTube", author: snippet.authorDisplayName || null, url: `https://www.youtube.com/watch?v=${videoId}` }); } } return result; }
function analyze(items: any[], title: string) { const pros: any[] = [], cons: any[] = [], positiveReviews: any[] = [], negativeReviews: any[] = []; const stats = new Map<string, { pro: number; con: number; examples: string[] }>(); let positive = 0, negative = 0; for (const review of items) for (const sentence of String(review.text).split(/[.!?]+/).map((part) => part.trim()).filter(Boolean)) { const words = sentence.toLowerCase().replace(/[^a-z0-9\s']/g, " ").split(/\s+/).filter(Boolean); const score = words.reduce((total, word) => total + (positiveWords.has(word) ? 1 : negativeWords.has(word) ? -1 : 0), 0); if (!score) continue; const found = Object.entries(aspects).filter(([, wordsForAspect]) => wordsForAspect.some((word) => sentence.toLowerCase().includes(word))).map(([name]) => name); if (score > 0) { positive++; if (positiveReviews.length < 40) positiveReviews.push({ text: sentence, sentiment: "positive", aspects: found, ...review }); } else { negative++; if (negativeReviews.length < 40) negativeReviews.push({ text: sentence, sentiment: "negative", aspects: found, ...review }); } for (const aspect of found) { const value = stats.get(aspect) || { pro: 0, con: 0, examples: [] }; score > 0 ? value.pro++ : value.con++; if (value.examples.length < 3) value.examples.push(sentence); stats.set(aspect, value); } } stats.forEach((value, aspect) => { if (value.pro > value.con) pros.push({ aspect, pro_mentions: value.pro, con_mentions: value.con, examples: value.examples }); if (value.con > value.pro) cons.push({ aspect, pro_mentions: value.pro, con_mentions: value.con, examples: value.examples }); }); const total = positive + negative; const pct = total ? Math.round((positive / total) * 1000) / 10 : null; const verdict = pct == null ? "Not enough data" : pct >= 65 ? "Mostly Positive" : pct <= 35 ? "Mostly Negative" : "Mixed"; return { movie_title: title, reviews_analyzed: items.length, sentences_scored: total, overall_verdict: verdict, overall_positive_pct: pct, positive: pros.slice(0, 8), negative: cons.slice(0, 8), pros: pros.slice(0, 8), cons: cons.slice(0, 8), positive_reviews: positiveReviews, negative_reviews: negativeReviews, summary: total ? `Based on ${items.length} audience reviews, ${title} has a ${verdict.toLowerCase()} reception (${pct}% positive sentiment).` : `We couldn't find enough audience reviews for ${title} yet to generate a pros/cons summary.` }; }
async function full(id: string) { const movie = await details(id); let items: any[] = []; let sourceErrors: Record<string, string> | null = null; try { items = await reviews(movie.title); } catch (error) { sourceErrors = { youtube: errorMessage(error) }; } return { movie, analysis: { ...analyze(items, movie.title), source_errors: sourceErrors } }; }
export function registerCinemaRoutes(app: Express) {
  app.get("/api/health", (_req, res) => res.json({ status: "ok", missing_api_keys: [!process.env.TMDB_API_KEY ? "TMDB_API_KEY" : null, !process.env.YOUTUBE_API_KEY ? "YOUTUBE_API_KEY" : null].filter(Boolean), ready: Boolean(process.env.TMDB_API_KEY && process.env.YOUTUBE_API_KEY) }));
  app.get("/api/search", async (req, res) => { try { const query = String(req.query.q || "").trim(); if (!query) return res.status(400).json({ error: "Query param 'q' is required" }); const data = await tmdb<any>("/search/movie", { query, page: Number(req.query.page || 1) }); res.json({ query, page: data.page, total_results: data.total_results, total_pages: data.total_pages, results: (data.results || []).map(simplify) }); } catch (error) { res.status(502).json({ error: errorMessage(error) }); } });
  for (const [route, path] of [["popular", "/movie/popular"], ["now-playing", "/movie/now_playing"], ["upcoming", "/movie/upcoming"], ["top-rated", "/movie/top_rated"]] as const) app.get(`/api/movies/${route}`, async (req, res) => { try { const data = await tmdb<any>(path, { page: Number(req.query.page || 1) }); res.json({ page: data.page, total_pages: data.total_pages, results: (data.results || []).map(simplify) }); } catch (error) { res.status(502).json({ error: errorMessage(error) }); } });
  app.get("/api/movies/:id/full", async (req, res) => { try { res.json(await full(req.params.id)); } catch (error) { res.status(502).json({ error: errorMessage(error) }); } });
  app.get("/api/movies/:id", async (req, res) => { try { res.json(await details(req.params.id)); } catch (error) { res.status(502).json({ error: errorMessage(error) }); } });
  app.get("/api/movies/:id/analysis", async (req, res) => { try { res.json((await full(req.params.id)).analysis); } catch (error) { res.status(502).json({ error: errorMessage(error) }); } });
}
